CREATE OR REPLACE PROCEDURE NATIONALITY_INS
(nat_id NATIONALITY.NATIONALITY_ID%TYPE,
 nat_name NATIONALITY.NATIONALITY_NAME%TYPE)
AS
BEGIN
    INSERT INTO NATIONALITY(NATIONALITY_ID, NATIONALITY_NAME)
    VALUES (nat_id, nat_name);
    COMMIT;
END;


CREATE OR REPLACE PROCEDURE NATIONALITY_UPD
(nat_id NATIONALITY.NATIONALITY_ID%TYPE,
 new_nat_name NATIONALITY.NATIONALITY_NAME%TYPE)
AS
BEGIN
    UPDATE NATIONALITY SET NATIONALITY_NAME = new_nat_name
    WHERE NATIONALITY_ID = nat_id;
    COMMIT;
END;



CREATE OR REPLACE PROCEDURE DESTINATION_INS
(dest_id DESTINATION.DESTINATION_ID%TYPE,
 dest_city DESTINATION.CITY_NAME%TYPE,
 dest_nat_id DESTINATION.NATIONALITY_ID%TYPE)
AS
BEGIN
    INSERT INTO DESTINATION(DESTINATION_ID, CITY_NAME, NATIONALITY_ID)
    VALUES (dest_id, dest_city, dest_nat_id);
    COMMIT;
END;


CREATE OR REPLACE PROCEDURE DESTINATION_UPD
(dest_id DESTINATION.DESTINATION_ID%TYPE,
 new_city DESTINATION.CITY_NAME%TYPE,
 new_nat_id DESTINATION.NATIONALITY_ID%TYPE)
AS
BEGIN
    UPDATE DESTINATION SET CITY_NAME = new_city, NATIONALITY_ID = new_nat_id
    WHERE DESTINATION_ID = dest_id;
    COMMIT;
END;



CREATE OR REPLACE PROCEDURE PASSENGER_INS
(pass_id PASSENGER.PASSENGER_ID%TYPE,
 passp_id PASSENGER.PASSPORT_ID%TYPE,
 pass_name PASSENGER.PASSENGER_NAME%TYPE,
 pass_nat_id PASSENGER.NATIONALITY_ID%TYPE)
AS
BEGIN
    INSERT INTO PASSENGER(PASSENGER_ID, PASSPORT_ID, PASSENGER_NAME, NATIONALITY_ID)
    VALUES (pass_id, passp_id, pass_name, pass_nat_id);
    COMMIT;
END;


CREATE OR REPLACE PROCEDURE PASSENGER_UPD
(pass_id PASSENGER.PASSENGER_ID%TYPE,
 new_passport_id PASSENGER.PASSPORT_ID%TYPE,
 new_pass_name PASSENGER.PASSENGER_NAME%TYPE,
 new_nat_id PASSENGER.NATIONALITY_ID%TYPE)
AS
BEGIN
    UPDATE PASSENGER SET PASSPORT_ID = new_passport_id,
                         PASSENGER_NAME = new_pass_name,
                         NATIONALITY_ID = new_nat_id
    WHERE PASSENGER_ID = pass_id;
    COMMIT;
END;



CREATE OR REPLACE PROCEDURE COMP_INS
(comp_id COMPANY.COMPANY_ID%TYPE,
 comp_name COMPANY.COMPANY_NAME%TYPE)
AS
BEGIN
    INSERT INTO COMPANY(COMPANY_ID, COMPANY_NAME)
    VALUES (comp_id, comp_name);
    COMMIT;
END;


CREATE OR REPLACE PROCEDURE COMP_UPD
(comp_id COMPANY.COMPANY_ID%TYPE,
 new_comp_name COMPANY.COMPANY_NAME%TYPE)
AS
BEGIN
    UPDATE COMPANY SET COMPANY_NAME = new_comp_name
    WHERE COMPANY_ID = comp_id;
    COMMIT;
END;



CREATE OR REPLACE PROCEDURE MODEL_INS
(mod_id MODEL.MODEL_ID%TYPE,
 mod_name MODEL.MODEL_NAME%TYPE,
 mod_capacity MODEL.MODEL_CAPACITY%TYPE,
 mod_comp_id MODEL.COMPANY_ID%TYPE)
AS
BEGIN
    INSERT INTO MODEL(MODEL_ID, MODEL_NAME, MODEL_CAPACITY, COMPANY_ID)
    VALUES (mod_id, mod_name, mod_capacity, mod_comp_id);
    COMMIT;
END;


CREATE OR REPLACE PROCEDURE MODEL_UPD
(mod_id MODEL.MODEL_ID%TYPE,
 new_mod_name MODEL.MODEL_NAME%TYPE,
 new_mod_capacity MODEL.MODEL_CAPACITY%TYPE,
 new_comp_id MODEL.COMPANY_ID%TYPE)
AS
BEGIN
    UPDATE MODEL SET MODEL_NAME = new_mod_name,
                     MODEL_CAPACITY = new_mod_capacity,
                     COMPANY_ID = new_comp_id
    WHERE MODEL_ID = mod_id;
    COMMIT;
END;



CREATE OR REPLACE PROCEDURE PLANE_INS
(pl_id PLANE.PLANE_ID%TYPE,
 plane_mod_id PLANE.MODEL_ID%TYPE)
AS
BEGIN
    INSERT INTO PLANE(PLANE_ID, MODEL_ID)
    VALUES (pl_id, plane_mod_id);
    COMMIT;
END;


CREATE OR REPLACE PROCEDURE PLANE_UPD
(pl_id PLANE.PLANE_ID%TYPE,
 new_mod_id PLANE.MODEL_ID%TYPE)
AS
BEGIN
    UPDATE PLANE SET MODEL_ID = new_mod_id
    WHERE PLANE_ID = pl_id;
    COMMIT;
END;



CREATE OR REPLACE PROCEDURE FLIGHT_INS
(fl_id FLIGHT.FLIGHT_ID%TYPE,
 fl_date FLIGHT.FLIGHT_DATE%TYPE,
 flight_price FLIGHT.PRICE%TYPE,
 flight_plane_id FLIGHT.PLANE_ID%TYPE,
 flight_from FLIGHT.FROM_DESTINATION_ID%TYPE,
 flight_to FLIGHT.TO_DESTINATION_ID%TYPE)
AS
BEGIN
    INSERT INTO FLIGHT(FLIGHT_ID, FLIGHT_DATE, PRICE, PLANE_ID, FROM_DESTINATION_ID, TO_DESTINATION_ID)
    VALUES (fl_id, fl_date, flight_price, flight_plane_id, flight_from, flight_to);
    COMMIT;
END;


CREATE OR REPLACE PROCEDURE FLIGHT_UPD
(fl_id FLIGHT.FLIGHT_ID%TYPE,
 new_flight_date FLIGHT.FLIGHT_DATE%TYPE,
 new_price FLIGHT.PRICE%TYPE,
 new_plane_id FLIGHT.PLANE_ID%TYPE,
 new_from FLIGHT.FROM_DESTINATION_ID%TYPE,
 new_to FLIGHT.TO_DESTINATION_ID%TYPE)
AS
BEGIN
    UPDATE FLIGHT SET FLIGHT_DATE = new_flight_date,
                      PRICE = new_price,
                      PLANE_ID = new_plane_id,
                      FROM_DESTINATION_ID = new_from,
                      TO_DESTINATION_ID = new_to
    WHERE FLIGHT_ID = fl_id;
    COMMIT;
END;



CREATE OR REPLACE PROCEDURE POSITION_INS
(pos_id POSITION.POSITION_ID%TYPE,
 pos_name POSITION.POSITION_NAME%TYPE)
AS
BEGIN
    INSERT INTO POSITION(POSITION_ID, POSITION_NAME)
    VALUES (pos_id, pos_name);
    COMMIT;
END;


CREATE OR REPLACE PROCEDURE POSITION_UPD
(pos_id POSITION.POSITION_ID%TYPE,
 new_pos_name POSITION.POSITION_NAME%TYPE)
AS
BEGIN
    UPDATE POSITION SET POSITION_NAME = new_pos_name
    WHERE POSITION_ID = pos_id;
    COMMIT;
END;



CREATE OR REPLACE PROCEDURE EMPLOYEE_INS
(emp_id EMPLOYEE.EMPLOYEE_ID%TYPE,
 emp_name EMPLOYEE.EMPLOYEE_NAME%TYPE,
 emp_phone EMPLOYEE.PHONE_NUMBER%TYPE,
 emp_pos_id EMPLOYEE.POSITION_ID%TYPE)
AS
BEGIN
    INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, PHONE_NUMBER, POSITION_ID)
    VALUES (emp_id, emp_name, emp_phone, emp_pos_id);
    COMMIT;
END;


CREATE OR REPLACE PROCEDURE EMPLOYEE_UPD
(emp_id EMPLOYEE.EMPLOYEE_ID%TYPE,
 new_emp_name EMPLOYEE.EMPLOYEE_NAME%TYPE,
 new_phone EMPLOYEE.PHONE_NUMBER%TYPE,
 new_pos_id EMPLOYEE.POSITION_ID%TYPE)
AS
BEGIN
    UPDATE EMPLOYEE SET EMPLOYEE_NAME = new_emp_name,
                        PHONE_NUMBER = new_phone,
                        POSITION_ID = new_pos_id
    WHERE EMPLOYEE_ID = emp_id;
    COMMIT;
END;



CREATE OR REPLACE PROCEDURE SEATCLASS_INS
(sc_id SEATCLASS.SEAT_CLASS_ID%TYPE,
 sc_name SEATCLASS.SEAT_CLASS_NAME%TYPE,
 sc_discount SEATCLASS.PERCENT_DISCOUNT%TYPE)
AS
BEGIN
    INSERT INTO SEATCLASS(SEAT_CLASS_ID, SEAT_CLASS_NAME, PERCENT_DISCOUNT)
    VALUES (sc_id, sc_name, sc_discount);
    COMMIT;
END;


CREATE OR REPLACE PROCEDURE SEATCLASS_UPD
(sc_id SEATCLASS.SEAT_CLASS_ID%TYPE,
 new_sc_name SEATCLASS.SEAT_CLASS_NAME%TYPE,
 new_discount SEATCLASS.PERCENT_DISCOUNT%TYPE)
AS
BEGIN
    UPDATE SEATCLASS SET SEAT_CLASS_NAME = new_sc_name,
                         PERCENT_DISCOUNT = new_discount
    WHERE SEAT_CLASS_ID = sc_id;
    COMMIT;
END;



CREATE OR REPLACE PROCEDURE SEAT_INS
(s_id SEAT.SEAT_ID%TYPE,
 s_name SEAT.SEAT_NAME%TYPE,
 s_class_id SEAT.SEAT_CLASS_ID%TYPE,
 seat_plane_id SEAT.PLANE_ID%TYPE)
AS
BEGIN
    INSERT INTO SEAT(SEAT_ID, SEAT_NAME, SEAT_CLASS_ID, PLANE_ID)
    VALUES (s_id, s_name, s_class_id, seat_plane_id);
    COMMIT;
END;


CREATE OR REPLACE PROCEDURE SEAT_UPD
(s_id SEAT.SEAT_ID%TYPE,
 new_seat_name SEAT.SEAT_NAME%TYPE,
 new_class_id SEAT.SEAT_CLASS_ID%TYPE,
 new_plane_id SEAT.PLANE_ID%TYPE)
AS
BEGIN
    UPDATE SEAT SET SEAT_NAME = new_seat_name,
                    SEAT_CLASS_ID = new_class_id,
                    PLANE_ID = new_plane_id
    WHERE SEAT_ID = s_id;
    COMMIT;
END;



CREATE OR REPLACE PROCEDURE TICKET_INS
(t_id TICKET.TICKET_ID%TYPE,
 ticket_seat_id TICKET.SEAT_ID%TYPE,
 ticket_flight_id TICKET.FLIGHT_ID%TYPE,
 ticket_pass_id TICKET.PASSENGER_ID%TYPE,
 ticket_emp_id TICKET.EMPLOYEE_ID%TYPE)
AS
BEGIN
    INSERT INTO TICKET(TICKET_ID, SEAT_ID, FLIGHT_ID, PASSENGER_ID, EMPLOYEE_ID)
    VALUES (t_id, ticket_seat_id, ticket_flight_id, ticket_pass_id, ticket_emp_id);
    COMMIT;
END;


CREATE OR REPLACE PROCEDURE TICKET_UPD
(t_id TICKET.TICKET_ID%TYPE,
 new_seat_id TICKET.SEAT_ID%TYPE,
 new_flight_id TICKET.FLIGHT_ID%TYPE,
 new_pass_id TICKET.PASSENGER_ID%TYPE,
 new_emp_id TICKET.EMPLOYEE_ID%TYPE)
AS
BEGIN
    UPDATE TICKET SET SEAT_ID = new_seat_id,
                      FLIGHT_ID = new_flight_id,
                      PASSENGER_ID = new_pass_id,
                      EMPLOYEE_ID = new_emp_id
    WHERE TICKET_ID = t_id;
    COMMIT;
END;



BEGIN
    NATIONALITY_INS(9, 'China');
END;

BEGIN
    NATIONALITY_UPD(9, 'Chinese');
END;


BEGIN
    DESTINATION_INS(9, 'Pekin', 9);
END;

BEGIN
    DESTINATION_UPD(9, 'Beijing', 9);
END;


BEGIN
    PASSENGER_INS(11, 1011, 'Sin Zin Min', 9);
END;

BEGIN
    PASSENGER_UPD(11, 1011, 'Sin Zin Pin', 9);
END;


BEGIN
    COMP_INS(4, 'Botash');
END;

BEGIN
    COMP_UPD(4, 'Botashhh');
END;


BEGIN
    MODEL_INS(6, 'Boeing 787', 250, 1);
END;

BEGIN
    MODEL_UPD(6, 'Boeing 787X', 270, 1);
END;


BEGIN
    PLANE_INS(9, 6);
END;

BEGIN
    PLANE_UPD(9, 5);
END;


BEGIN
    FLIGHT_INS(13, TIMESTAMP '2025-08-01 10:00:00', 300.00, 9, 1, 2);
END;

BEGIN
    FLIGHT_UPD(13, TIMESTAMP '2025-08-01 11:00:00', 320.00, 9, 1, 2);
END;


BEGIN
    POSITION_INS(4, 'Engineer');
END;

BEGIN
    POSITION_UPD(4, 'Chief Engineer');
END;


BEGIN
    EMPLOYEE_INS(9, 'Tom Black', '+1234567898', 4);
END;

BEGIN
    EMPLOYEE_UPD(9, 'Thomas Black', '+1234567898', 4);
END;


BEGIN
    SEATCLASS_INS(4, 'Premium', 15);
END;

BEGIN
    SEATCLASS_UPD(4, 'Premium Plus', 20);
END;


BEGIN
    SEAT_INS(19, '2A', 2, 9);
END;

BEGIN
    SEAT_UPD(19, '2B', 2, 9);
END;


BEGIN
    TICKET_INS(25, 19, 11, 1, 9);
END;

BEGIN
    TICKET_UPD(25, 19, 11, 2, 9);
END;

