-- Тьреене на полети по: дестинация, дата, авиокомпания.
SELECT
    f.FLIGHT_DATE,
    d_from.CITY_NAME,
    d_to.CITY_NAME,
    f.PRICE,
    m.MODEL_NAME,
    c.COMPANY_NAME
FROM
    FLIGHT f
JOIN
    DESTINATION d_from
ON
    f.FROM_DESTINATION_ID = d_from.DESTINATION_ID
JOIN
    DESTINATION d_to
ON
    f.TO_DESTINATION_ID = d_to.DESTINATION_ID
JOIN
    PLANE p
ON
    p.PLANE_ID = f.PLANE_ID
JOIN
    MODEL m
ON
    m.MODEL_ID = p.MODEL_ID
JOIN
    Company c
ON
    c.COMPANY_ID = m.COMPANY_ID
WHERE
    d_to.city_name = 'New York'
--     TRUNC(f.flight_date) = Date '2025-07-01'
--     c.COMPANY_NAME = 'Boeing'
ORDER BY f.FLIGHT_DATE
;


-- пътници на полет;
SELECT
    f.FLIGHT_DATE,
    d_from.CITY_NAME,
    d_to.CITY_NAME,
    p.PASSPORT_ID,
    p.PASSENGER_NAME,
    s.SEAT_NAME,
    sc.SEAT_CLASS_NAME
FROM
    Ticket t
JOIN
    FLIGHT f
ON
    t.FLIGHT_ID = f.FLIGHT_ID
JOIN
    DESTINATION d_from
ON
    f.FROM_DESTINATION_ID = d_from.DESTINATION_ID
JOIN
    DESTINATION d_to
ON
    f.TO_DESTINATION_ID = d_to.DESTINATION_ID
JOIN
    PASSENGER p
ON
    t.PASSENGER_ID = p.PASSENGER_ID
JOIN
    SEAT s
ON
    t.SEAT_ID = s.SEAT_ID
JOIN
    SEATCLASS sc
ON
    sc.SEAT_CLASS_ID = s.SEAT_CLASS_ID
WHERE
    d_from.CITY_NAME = 'Sofia'
    AND d_to.CITY_NAME = 'Paris'
    AND f.FLIGHT_DATE = TIMESTAMP '2025-07-20 11:30:00'
ORDER BY p.PASSPORT_ID
;

SELECT
    f.FLIGHT_DATE,
    d_from.CITY_NAME,
    d_to.CITY_NAME
from
    FLIGHT f
JOIN
    DESTINATION d_from
ON
    d_from.DESTINATION_ID = f.FROM_DESTINATION_ID
JOIN
    DESTINATION d_to
ON
    d_to.DESTINATION_ID = f.TO_DESTINATION_ID
;


-- заетост на самолет;
SELECT
    (select f.FLIGHT_DATE from FLIGHT f where f.FLIGHT_ID = t.FLIGHT_ID) as FLIGHT_DATE,
    MAX(d_from.CITY_NAME) as FROM_CITY,
    MAX(d_to.CITY_NAME) as TO_CITY,
    MAX(m.MODEL_NAME) as MODEL,
    MAX(c.COMPANY_NAME) as COMPANY,
    COUNT(t.TICKET_ID) as SEATS_OCCUPIED,
    MAX(m.MODEL_CAPACITY) AS SEATS_CAPACITY
FROM
    TICKET t
JOIN
    FLIGHT f
ON
    t.FLIGHT_ID = f.FLIGHT_ID
JOIN
    DESTINATION d_from
ON
    f.FROM_DESTINATION_ID = d_from.DESTINATION_ID
JOIN
    DESTINATION d_to
ON
    f.TO_DESTINATION_ID = d_to.DESTINATION_ID
JOIN
    PLANE p
ON
    p.PLANE_ID = f.PLANE_ID
JOIN
    MODEL m
ON
    m.MODEL_ID = p.MODEL_ID
JOIN
    Company c
ON
    c.COMPANY_ID = m.COMPANY_ID
GROUP BY
    t.FLIGHT_ID
ORDER BY
    (select f.FLIGHT_DATE from FLIGHT f where f.FLIGHT_ID = t.FLIGHT_ID)
;


--приходи от билети за период.

-- DEFINE from_date = TIMESTAMP '2025-06-01 00:00:00';
-- DEFINE to_date = TIMESTAMP '2025-07-31 23:59:59';
SELECT
    TIMESTAMP '2025-06-01 00:00:00' as FROM_DATE,
    TIMESTAMP '2025-07-31 23:59:59' as TO_DATE,
    COUNT(t.TICKET_ID) as TOTAL_TICKETS,
    SUM(f.PRICE + (sc.PERCENT_DISCOUNT / 100) * f.PRICE) AS TOTAL_REVENUE
FROM
    TICKET t
JOIN
    FLIGHT f
ON
    t.FLIGHT_ID = f.FLIGHT_ID
JOIN
    SEAT s
ON
    t.SEAT_ID = s.SEAT_ID
JOIN
    SEATCLASS sc
ON
    s.SEAT_CLASS_ID = sc.SEAT_CLASS_ID
WHERE
    f.FLIGHT_DATE BETWEEN TIMESTAMP '2025-06-01 00:00:00' AND TIMESTAMP '2025-07-31 23:59:59'
;


-- Най-печеливши дестинации за период. - топ 5
SELECT
--     d.CITY_NAME,
    (SELECT d.CITY_NAME from DESTINATION d where d.DESTINATION_ID = f.TO_DESTINATION_ID) AS City,
    COUNT(t.TICKET_ID) as TOTAL_TICKETS,
    ROUND(SUM(f.PRICE + (sc.PERCENT_DISCOUNT / 100) * f.PRICE), 2) AS TOTAL_REVENUE
FROM
    TICKET t
JOIN
    FLIGHT f
ON
    t.FLIGHT_ID = f.FLIGHT_ID
JOIN
    SEAT s
ON
    t.SEAT_ID = s.SEAT_ID
JOIN
    SEATCLASS sc
ON
    s.SEAT_CLASS_ID = sc.SEAT_CLASS_ID
WHERE
    f.FLIGHT_DATE BETWEEN TIMESTAMP '2025-06-01 00:00:00' AND TIMESTAMP '2025-07-31 23:59:59'
GROUP BY f.TO_DESTINATION_ID
ORDER BY TOTAL_REVENUE DESC
    FETCH FIRST 5 ROWS ONLY
;


-- Клиенти с >=3 пьтувания в последните 6 месеца.
SELECT
    (SELECT p.PASSENGER_NAME from PASSENGER p where p.PASSENGER_ID = t.PASSENGER_ID) AS NAME,
    (SELECT n.NATIONALITY_NAME from PASSENGER p JOIN NATIONALITY n ON n.NATIONALITY_ID = p.NATIONALITY_ID where p.PASSENGER_ID = t.PASSENGER_ID) AS NATIONALITY,
--     p.PASSENGER_NAME,
--     n.NATIONALITY_NAME AS NATIONALITY,
    COUNT(t.TICKET_ID) AS TOTAL_TRIPS
FROM
    TICKET t
JOIN
    FLIGHT f
ON
    t.FLIGHT_ID = f.FLIGHT_ID
WHERE
    f.FLIGHT_DATE >= ADD_MONTHS(SYSDATE, -18)
GROUP BY t.PASSENGER_ID
HAVING
    COUNT(t.PASSENGER_ID) >= 3
ORDER BY TOTAL_TRIPS DESC
;

