-- Тьреене на полети по: дестинация, дата, авиокомпания.
SELECT
    f.FLIGHT_ID,
    f.FLIGHT_DATE,
    d_from.CITY_NAME,
    d_to.CITY_NAME,
    f.PRICE,
    m.MODEL_NAME,
    c.COMPANY_NAME
FROM
    FLIGHT f
JOIN
    DESTINATION d_from
ON
    f.TO_DESTINATION_ID = d_from.DESTINATION_ID
JOIN
    DESTINATION d_to
ON
    f.FROM_DESTINATION_ID = d_to.DESTINATION_ID
JOIN
    PLANE p
ON
    p.PLANE_ID = f.PLANE_ID
JOIN
    MODEL m
ON
    m.MODEL_ID = p.MODEL_ID
JOIN
    Company c
ON
    c.COMPANY_ID = m.COMPANY_ID
WHERE
    --d_to.city_name = 'London'
    --f.flight_date = ''
    c.COMPANY_NAME = 'Boeing'
;


-- пътници на полет;
SELECT
    t.FLIGHT_ID,
    f.FLIGHT_DATE,
    d_from.CITY_NAME,
    d_to.CITY_NAME,
    p.PASSPORT_ID,
    p.PASSENGER_NAME
FROM
    Ticket t
JOIN
    FLIGHT f
ON
    t.FLIGHT_ID = f.FLIGHT_ID
JOIN
    DESTINATION d_from
ON
    f.FROM_DESTINATION_ID = d_from.DESTINATION_ID
JOIN
    DESTINATION d_to
ON
    f.TO_DESTINATION_ID = d_to.DESTINATION_ID
JOIN
    PASSENGER p
ON
    t.PASSENGER_ID = p.PASSENGER_ID
WHERE
    t.FLIGHT_ID = 8
;


-- заетост на самолет;
SELECT
    f.FLIGHT_ID,
    f.FLIGHT_DATE,
    d_from.CITY_NAME,
    d_to.CITY_NAME,
    m.MODEL_NAME,
    c.COMPANY_NAME,
    COUNT(t.TICKET_ID) as SEATS_OCCUPIED,
    m.MODEL_CAPACITY as SEATS_CAPACITY
FROM
    TICKET t
JOIN
    FLIGHT f
ON
    t.FLIGHT_ID = f.FLIGHT_ID
JOIN
    DESTINATION d_from
ON
    f.FROM_DESTINATION_ID = d_from.DESTINATION_ID
JOIN
    DESTINATION d_to
ON
    f.TO_DESTINATION_ID = d_to.DESTINATION_ID
JOIN
    PLANE p
ON
    p.PLANE_ID = f.PLANE_ID
JOIN
    MODEL m
ON
    m.MODEL_ID = p.MODEL_ID
JOIN
    Company c
ON
    c.COMPANY_ID = m.COMPANY_ID
GROUP BY
    f.FLIGHT_ID, f.FLIGHT_DATE, d_from.CITY_NAME, d_to.CITY_NAME, m.MODEL_NAME, c.COMPANY_NAME, m.MODEL_CAPACITY
ORDER BY
    f.FLIGHT_ID
;


--приходи от билети за период.

-- DEFINE from_date = TIMESTAMP '2025-06-01 00:00:00';
-- DEFINE to_date = TIMESTAMP '2025-07-31 23:59:59';
SELECT
    TIMESTAMP '2025-06-01 00:00:00' as FROM_DATE,
    TIMESTAMP '2025-07-31 23:59:59' as TO_DATE,
    COUNT(t.TICKET_ID) as TOTAL_TICKETS,
    SUM(f.PRICE + (sc.PERCENT_DISCOUNT / 100) * f.PRICE) AS TOTAL_REVENUE
FROM
    TICKET t
JOIN
    FLIGHT f
ON
    t.FLIGHT_ID = f.FLIGHT_ID
JOIN
    SEAT s
ON
    t.SEAT_ID = s.SEAT_ID
JOIN
    SEATCLASS sc
ON
    s.SEAT_CLASS_ID = sc.SEAT_CLASS_ID
WHERE
    f.FLIGHT_DATE BETWEEN TIMESTAMP '2025-06-01 00:00:00' AND TIMESTAMP '2025-07-31 23:59:59'
;


-- Най-печеливши дестинации за период. - топ 5
SELECT
    d.CITY_NAME,
    COUNT(t.TICKET_ID) as TOTAL_TICKETS,
    ROUND(SUM(f.PRICE + (sc.PERCENT_DISCOUNT / 100) * f.PRICE), 2) AS TOTAL_REVENUE
FROM
    TICKET t
JOIN
    FLIGHT f
ON
    t.FLIGHT_ID = f.FLIGHT_ID
JOIN
    SEAT s
ON
    t.SEAT_ID = s.SEAT_ID
JOIN
    SEATCLASS sc
ON
    s.SEAT_CLASS_ID = sc.SEAT_CLASS_ID
JOIN
    DESTINATION d
ON
    f.TO_DESTINATION_ID = d.DESTINATION_ID
WHERE
    f.FLIGHT_DATE BETWEEN TIMESTAMP '2025-06-01 00:00:00' AND TIMESTAMP '2025-07-31 23:59:59'
GROUP BY d.CITY_NAME
ORDER BY TOTAL_REVENUE DESC
FETCH FIRST 5 ROWS ONLY
;


-- Клиенти с >=3 пьтувания в последните 6 месеца.
SELECT
    p.PASSENGER_NAME,
    n.NATIONALITY_NAME AS NATIONALITY,
    COUNT(t.TICKET_ID) AS TOTAL_TRIPS
FROM
    TICKET t
JOIN
    FLIGHT f
ON
    t.FLIGHT_ID = f.FLIGHT_ID
JOIN
    PASSENGER p
ON
    t.PASSENGER_ID = p.PASSENGER_ID
JOIN
    NATIONALITY n
ON
    p.NATIONALITY_ID = n.NATIONALITY_ID
WHERE
    f.FLIGHT_DATE >= ADD_MONTHS(SYSDATE, -6)
--     f.FLIGHT_DATE BETWEEN TIMESTAMP '2025-06-01 00:00:00' AND TIMESTAMP '2025-07-31 23:59:59'
GROUP BY p.PASSENGER_NAME, n.NATIONALITY_NAME
HAVING
    COUNT(t.TICKET_ID) >= 3
ORDER BY TOTAL_TRIPS DESC
;
